### ISSUE TITLE
XML document error

### ISSUE THREAD

**Issue by ghost** [RickDB/PlexMALSync#1]
```
System.InvalidOperationException: There is an error in XML document (1, 1). ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderAnimeSearchResponse.Read5_anime()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at MyAnimeListSharp.Util.SearchResponseDeserializer`1.Deserialize(String responseString)
   at MyAnimeListSharp.Facade.Async.AnimeSearchMethodsAsync.<>c__DisplayClass2_0.<SearchDeserializedAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyAnimeListSharp.Facade.Async.AnimeSearchMethodsAsync.<SearchDeserializedAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlexMALSync.Program.<ProcessAnime>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlexMALSync.Program.<ProcesPlexSections>d__5.MoveNext()
```

It worked for a few series and then I was hit with this issue. Tried rerunning and then this happens every time.

**Comment by RickDB** [comment]
Sorry about the delay, this is due to the MAL API temporarily blocking login for an unknown reason as you will see new logins blocked for a few hours on their site as well.

Trying to figure out if it's due to it not caching credentials or that the library we use (MyAnimeListSharp) is incompatible with current MAL API.

**Comment by RickDB** [comment]
@nowak94 Rewritten to Python and tested working, instructions updated in readme.
As it's completely rewritten bugs can happen but please let me know if you spot any.
