### ISSUE TITLE
Sync Problem

### ISSUE THREAD

**Issue by nanulf** [RickDB/PlexMALSync#10]
Hi, I've been testing the application and I think I found a bug.
My system has these features:
Python 3.6.4
plex-media-server 1.12.3.4947

Log:
====
```
2018-04-13 20:18:53 [PLEX] Retrieving anime shows...
2018-04-13 20:18:53 [PLEX] Retrieving of 196 anime shows completed
2018-04-13 20:18:53 [PLEX] Retrieving watch count for shows...
2018-04-13 20:18:53 Watched 13 episodes of show: 91 Days
(...)
2018-04-13 20:19:08 Watched 22 episodes of show: Your Lie in April
2018-04-13 20:19:08 [PLEX] Retrieving watch count for shows finished
2018-04-13 20:19:08 [MAL] Retrieving list...
2018-04-13 20:19:10 [MAL] Found 99 shows on list
2018-04-13 20:19:10 [MAL] Matching seasons inside MAL list...
2018-04-13 20:19:10 [MAL] Matching seasons inside MAL list finished
2018-04-13 20:19:10 [MAL] Retrieving updated list for season matching...
Traceback (most recent call last):
  File "PlexMALSync.py", line 448, in <module>
    start()
  File "PlexMALSync.py", line 441, in start
    mal_list_seasoned, watched_shows)
  File "PlexMALSync.py", line 183, in update_mal_list_with_seasons
    show, , mal_credentials)
  File "/var/lib/mal/mal/lib/python3.6/site-packages/spice_api/spice.py", line 152, in search
    if len(query) == 0:
TypeError: object of type 'Show' has no len()
```
The problem is on line 183, you need to change this:
```
show, spice.get_medium('anime'), mal_credentials)
show.title, spice.get_medium('anime'), mal_credentials)
```
After making the change everything works correctly.

Thanks for the application.

**Comment by RickDB** [comment]
Thanks for reporting, pushed your fix 👍
