### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 66: ordinal not in range(128)

### ISSUE THREAD

**Issue by nsater** [RickDB/PlexMALSync#11]
Hello,

I am seeing this error on a number of different shows.  For example the anime 'A Place Further Than the Universe' throws up this error no matter what episode is watched (one, two or, all), but marking them all unwatched, temporally fixes the issue because the script skips the show. 

The script parses other shows without issue, but I don't see a pattern to the ones that cause the issue. Let me know if you need more information or what I can do to help.

Thanks.

Traceback (most recent call last):
  File "PlexMALSync.py", line 447, in <module>
    start()
  File "PlexMALSync.py", line 433, in start
    watched_shows = get_plex_watched_shows(shows)
  File "PlexMALSync.py", line 107, in get_plex_watched_shows
    watched[show] = (episodes_watched, season_watched)
  File "/home/neil/.local/lib/python2.7/site-packages/plexapi/base.py", line 266, in __hash__
    return hash(repr(self))
  File "/home/neil/.local/lib/python2.7/site-packages/plexapi/base.py", line 51, in __repr__
    name = self._clean(self.firstAttr('title', 'name', 'username', 'product', 'tag', 'value'))
  File "/home/neil/.local/lib/python2.7/site-packages/plexapi/base.py", line 62, in _clean
    value = str(value).replace('/library/metadata/', '')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 66: ordinal not in `range(128)

![2018-05-16 16_38_38-plex](https://user-images.githubusercontent.com/30016839/40149392-222da02c-5928-11e8-8562-853b6a6e85ff.png)

**Comment by nsater** [comment]
Sorry, issue was with python. My Debian box was reverting to 2.7. Works fine with 3.6
